language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - npm install -g codecov
script:
  - yarn build:sync
  - yarn test
  - codecov
  - yarn build:dist # the dist build is only used to track bundle size delta
  - yarn bundlesize
  - if [ $TRAVIS_EVENT_TYPE = 'push' ]; then 
    - if [ $TRAVIS_BRANCH != 'master' ]; then
      yarn chromatic
    else
      # We know any changes that make it to master *must* have been approved
      yarn chromatic --auto-accept-changes
  fi
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc # we only want to run this on deploys as this guarantees we have an NPM_TOKEN env var
  # only create releases folder once, before_deploy gets called before every provider so save time by only doing once
  - if [ ! -d "releases" ]; then yarn run pack && mkdir releases && mv {components,packages}/*/govuk-react-*.tgz ./releases; fi
  - LERNA_VERSION=$(node -e 'console.log(require("./lerna.json").version)')
deploy:
  - provider: pages # https://docs.travis-ci.com/user/deployment/pages/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: packages/storybook/storybook-static
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: lerna exec --no-private --bail=false -- "can-npm-publish && npm publish"
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "releases/govuk-react-*-${LERNA_VERSION}.tgz"
    skip_cleanup: true
    on:
      tags: true
