language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - yarn bootstrap
  - npm install -g codecov
script:
  - yarn build
  - yarn test
  - codecov
  - yarn build:dist # the dist build is only used to track bundle size delta
  - yarn bundlesize
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc # we only want to run this on deploys as this guarantees we have an NPM_TOKEN env var
  # only create releases folder once, before_deploy gets called before every provider so save time by only doing once
  - if [ ! -d "releases" ]; then yarn run pack && mkdir releases && mv {components,packages}/*/govuk-react-*.tgz ./releases; fi
deploy:
  - provider: pages # https://docs.travis-ci.com/user/deployment/pages/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: storybook-static
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: lerna exec --no-private --bail=false -- "can-npm-publish && npm publish"
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "{components,packages}/*/govuk-react-*.tgz"
    skip_cleanup: true
    on:
      tags: true
